In [1]:
import pandas as pd

In [2]:
data_frame = pd.read_csv(r"D:\Second year second semester\Python for data science\Data Set\Data Sets-20240826\pokemon.csv")

In [3]:
data_frame.shape

(801, 41)

In [4]:
data_frame.head()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
0,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,1,65,65,45,grass,poison,6.9,1,0
1,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,2,80,80,60,grass,poison,13.0,1,0
2,"['Overgrow', 'Chlorophyll']",1.0,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,88.1,3,122,120,80,grass,poison,100.0,1,0
3,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,4,60,50,65,fire,NaN,8.5,1,0
4,"['Blaze', 'Solar Power']",0.5,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,88.1,5,80,65,80,fire,NaN,19.0,1,0

In [5]:
data_frame.tail()

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,percentage_male,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
796,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,NaN,797,107,101,61,steel,flying,999.9,7,1
797,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,NaN,798,59,31,109,grass,steel,0.1,7,1
798,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,NaN,799,97,53,43,dark,dragon,888.0,7,1
799,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,NaN,800,127,89,79,psychic,NaN,230.0,7,1
800,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,NaN,801,130,115,65,steel,fairy,80.5,7,1

In [6]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 41 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   abilities          801 non-null    object
 1   against_bug        801 non-null    float64
 2   against_dark       801 non-null    float64
 3   against_dragon     801 non-null    float64
 4   against_electric   801 non-null    float64
 5   against_fairy      801 non-null    float64
 6   against_fight      801 non-null    float64
 7   against_fire       801 non-null    float64
 8   against_flying     801 non-null    float64
 9   against_ghost      801 non-null    float64
 10  against_grass      801 non-null    float64
 11  against_ground     801 non-null    float64
 12  against_ice        801 non-null    float64
 13  against_normal     801 non-null    float64
 14  against_poison     801 non-null    float64
 15  against_psychic    801 non-null    float64
 16  against_rock       801 non-null    float64
 17  against_steel      801 non-null    float64
 18  against_water      801 non-null    float64
 19  attack             801 non-null    int64
 20  base_egg_steps     801 non-null    int64
 21  base_happiness     801 non-null    int64
 22  base_total         801 non-null    int64
 23  capture_rate       801 non-null    object
 24  classfication      801 non-null    object
 25  defense            801 non-null    int64
 26  experience_growth  801 non-null    int64
 27  height_m           781 non-null    float64
 28  hp                 801 non-null    int64
 29  japanese_name      801 non-null    object
 30  name               801 non-null    object
 31  percentage_male    703 non-null    float64
 32  pokedex_number     801 non-null    int64
 33  sp_attack          801 non-null    int64
 34  sp_defense         801 non-null    int64
 35  speed              801 non-null    int64
 36  type1              801 non-null    object
 37  type2              417 non-null    object
 38  weight_kg          781 non-null    float64
 39  generation         801 non-null    int64
 40  is_legendary       801 non-null    int64
dtypes: float64(21), int64(13), object(7)
memory usage: 256.7+ KB

Find Average hp

In [7]:
data_frame['hp']

0       45
1       60
2       80
3       39
4       58
      ...
796     97
797     59
798    223
799     97
800     80
Name: hp, Length: 801, dtype: int64

In [9]:
data_frame[['hp', 'attack', 'defense']].mean()

hp         68.958801
attack     77.857678
defense    73.008739
dtype: float64

Display only fire-type pokemon in columns 'name', 'type1', 'hp', 'attack'

In [18]:
data_filtering = data_frame[data_frame['type1'] == 'fire'][['name', 'hp', 'attack']].head()

print(data_filtering)

          name  hp  attack
3   Charmander  39      52
4   Charmeleon  58      64
5    Charizard  78     104
36      Vulpix  38      41
37   Ninetales  73      67

How many pokemon are there for each type in the Type1 column

In [21]:
data_frame['type1'].value_counts()

type1
water       114
normal      105
grass        78
bug          72
psychic      53
fire         52
rock         45
electric     39
poison       32
ground       32
dark         29
fighting     28
ghost        27
dragon       27
steel        24
ice          23
fairy        18
flying        3
Name: count, dtype: int64

In [22]:
data_frame[data_frame['attack'] > 100][['attack', 'name']]

     attack        name
5       104   Charizard
8       103   Blastoise
14      150    Beedrill
33      102    Nidoking
56      105    Primeape
..      ...         ...
794     137   Pheromosa
796     101  Celesteela
797     181     Kartana
798     101    Guzzlord
799     107    Necrozma

[169 rows x 2 columns]

Create a copy of orginal data frame

In [28]:
data_frame01 = data_frame.copy()

Rename the column

In [24]:
data_frame01 = data_frame01.rename(columns= {'hp':'health', 'attack': 'atk', 'defense':'def'})

In [26]:
data_frame01['atk'].head()

0     49
1     62
2    100
3     52
4     64
Name: atk, dtype: int64

In [29]:
data_frame01['total'] = data_frame01[['hp', 'attack', 'defense', 'speed']].sum(axis= 1)

In [31]:
data_frame01['total'].head(30)

0     188
1     245
2     383
3     199
4     260
5     360
6     200
7     260
8     380
9     155
10    155
11    225
12    155
13    155
14    400
15    181
16    249
17    364
18    193
19    293
20    200
21    320
22    194
23    304
24    220
25    305
26    255
27    360
28    195
29    255
Name: total, dtype: int64

In [33]:
data_frame01[data_frame01['is_legendary'] == True].head(20)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,pokedex_number,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary,total
143,"['Pressure', 'Snow Cloak']",0.50,1.0,1.0,2.0,1.0,1.00,2.0,1.0,1.0,...,144,95,125,85,ice,flying,55.4,1,1,360
144,"['Pressure', 'Static']",0.50,1.0,1.0,1.0,1.0,0.50,1.0,0.5,1.0,...,145,125,90,100,electric,flying,52.6,1,1,365
145,"['Pressure', 'Flame Body']",0.25,1.0,1.0,2.0,0.5,0.50,0.5,1.0,1.0,...,146,125,85,90,fire,flying,60.0,1,1,370
149,"['Pressure', 'Unnerve']",2.00,2.0,1.0,1.0,1.0,0.50,1.0,1.0,2.0,...,150,194,120,140,psychic,NaN,122.0,1,1,466
150,['Synchronize'],2.00,2.0,1.0,1.0,1.0,0.50,1.0,1.0,2.0,...,151,100,100,100,psychic,NaN,4.0,1,1,400
242,"['Pressure', 'Inner Focus']",1.00,1.0,1.0,0.5,1.0,1.00,1.0,0.5,1.0,...,243,115,100,115,electric,NaN,178.0,2,1,365
243,"['Pressure', 'Inner Focus']",0.50,1.0,1.0,1.0,0.5,1.00,0.5,1.0,1.0,...,244,90,75,100,fire,NaN,198.0,2,1,415
244,"['Pressure', 'Inner Focus']",1.00,1.0,1.0,2.0,1.0,1.00,0.5,1.0,1.0,...,245,90,115,85,water,NaN,187.0,2,1,375
248,"['Pressure', 'Multiscale']",1.00,2.0,1.0,2.0,1.0,0.25,1.0,1.0,2.0,...,249,90,154,110,psychic,flying,216.0,2,1,436
249,"['Pressure', 'Regenerator']",0.25,1.0,1.0,2.0,0.5,0.50,0.5,1.0,1.0,...,250,110,154,90,fire,flying,199.0,2,1,416
250,['Natural Cure'],4.00,2.0,1.0,0.5,1.0,0.50,2.0,2.0,2.0,...,251,100,100,100,psychic,grass,5.0,2,1,400
376,"['Clear Body', 'Sturdy']",1.00,1.0,1.0,1.0,1.0,2.00,0.5,0.5,1.0,...,377,50,100,50,rock,NaN,230.0,3,1,430
377,"['Clear Body', 'Ice Body']",1.00,1.0,1.0,1.0,1.0,2.00,2.0,1.0,1.0,...,378,100,200,50,ice,NaN,175.0,3,1,280
378,"['Clear Body', 'Light Metal']",0.50,1.0,0.5,1.0,0.5,2.00,2.0,0.5,1.0,...,379,75,150,50,steel,NaN,205.0,3,1,355
379,['Levitate'],2.00,2.0,2.0,0.5,2.0,0.50,0.5,1.0,2.0,...,380,140,150,110,dragon,psychic,40.0,3,1,410
380,['Levitate'],2.00,2.0,2.0,0.5,2.0,0.50,0.5,1.0,2.0,...,381,160,120,110,dragon,psychic,60.0,3,1,420
381,['Drizzle'],1.00,1.0,1.0,2.0,1.0,1.00,0.5,1.0,1.0,...,382,180,160,90,water,NaN,352.0,3,1,430
382,['Drought'],1.00,1.0,1.0,0.0,1.0,1.00,1.0,1.0,1.0,...,383,150,90,90,ground,NaN,950.0,3,1,530
383,['Air Lock'],0.50,1.0,2.0,1.0,2.0,0.50,0.5,1.0,1.0,...,384,180,100,115,dragon,flying,206.5,3,1,500
384,['Serene Grace'],1.00,2.0,0.5,1.0,0.5,1.00,2.0,0.5,2.0,...,385,100,100,100,steel,psychic,1.1,3,1,400

In [36]:
data_frame01[['attack', 'defense']].mean()

attack     77.857678
defense    73.008739
dtype: float64